name: Test

on:
  issues:
    types: [opened, labeled]

jobs:
  test_noto:
    run: |
     curl -X POST 'https://api.telegram.org/bot8275670284:AAECfL45PycZ8tYNRIw-mVRuAqzP8Hqn3RQ/sendMessage'
      -H 'Content-Type: application/json'
      -d '{
        "chat_id": "-1002923319232",
        "text": "Your message here"
        }'
